import NavBar from "./components/NavBar/page";
import Footer from "./components/Footer/page";

import "./globals.css";

export const metadata = {
  title: "Indy Laser Designs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
